Repository ghostery/adblocker, pull requests merged in 2020-11, with the labels that each got.

#1394 Add new request-allowed event
  packages/adblocker/src/engine/engine.ts
Labels: PR: Polish :nail_care:

#1427 Update puppeteer types to 5.x
  packages/adblocker-puppeteer/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#1451 Fix memory leak by using a WeakMap to hold context information in blocker
  packages/adblocker-electron/adblocker.ts
  packages/adblocker-playwright/adblocker.ts
  packages/adblocker-puppeteer/adblocker.ts
  packages/adblocker-webextension/adblocker.ts
Labels: PR: Bug Fix :bug:

#1466 Fix with newer Typescript + cleanups
  .github/workflows/tests.yml
  .metalint.json
  package.json
  packages/adblocker-content/adblocker.ts
  packages/adblocker-content/package.json
  packages/adblocker-content/rollup.config.ts
  packages/adblocker-electron-example/index.ts
  packages/adblocker-electron-example/package.json
  packages/adblocker-electron-preload/package.json
  packages/adblocker-electron-preload/preload.ts
  packages/adblocker-electron/package.json
  packages/adblocker-playwright-example/package.json
  packages/adblocker-playwright/adblocker.ts
  packages/adblocker-playwright/package.json
  packages/adblocker-puppeteer-example/index.ts
  packages/adblocker-puppeteer-example/package.json
  packages/adblocker-puppeteer/package.json
  packages/adblocker-webextension-cosmetics/adblocker.ts
  packages/adblocker-webextension-cosmetics/package.json
  packages/adblocker-webextension-cosmetics/rollup.config.ts
  packages/adblocker-webextension-example/package.json
  packages/adblocker-webextension/adblocker.ts
  packages/adblocker-webextension/package.json
  packages/adblocker-webextension/rollup.config.ts
  packages/adblocker/package.json
  packages/adblocker/rollup.config.ts
  packages/adblocker/src/data-view.ts
  packages/adblocker/src/engine/bucket/cosmetic.ts
  packages/adblocker/src/engine/bucket/filters.ts
  packages/adblocker/src/engine/bucket/network.ts
  packages/adblocker/src/engine/domains.ts
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/src/engine/optimizer.ts
  packages/adblocker/src/engine/reverse-index.ts
  packages/adblocker/src/events.ts
  packages/adblocker/src/fetch.ts
  packages/adblocker/src/filters/cosmetic.ts
  packages/adblocker/src/filters/network.ts
  packages/adblocker/src/html-filtering.ts
  packages/adblocker/src/lists.ts
  packages/adblocker/src/request.ts
  packages/adblocker/src/resources.ts
  packages/adblocker/src/utils.ts
  packages/adblocker/test/engine/engine.test.ts
  packages/adblocker/test/html-filtering.test.ts
  packages/adblocker/test/matching.test.ts
  packages/adblocker/test/optimizer.test.ts
  packages/adblocker/test/parsing.test.ts
  packages/adblocker/test/request.test.ts
  packages/adblocker/test/reverse-index.test.ts
  packages/adblocker/test/serialization.test.ts
  packages/adblocker/test/utils.test.ts
  packages/adblocker/tools/stress-test-engine-update.ts
  tsconfig.json
  yarn.lock
Labels: PR: Polish :nail_care:

#1469 Update create-pull-request action
  .github/workflows/assets.yml
Labels: PR: Internal :house:

#1471 Fix mathing of hostname filters with www.
  packages/adblocker/src/filters/network.ts
  packages/adblocker/test/data/requests.ts
Labels: PR: Bug Fix :bug:
