Repository ghostery/adblocker, pull requests merged in 2021-08, with the labels that each got.

#2093 Use minified version of Cliqz
  packages/adblocker-benchmarks/blockers/cliqz-base.js
Labels: PR: Internal :house:

#2101 Use bundle.min.cjs for adblockplus
  packages/adblocker-benchmarks/Makefile
  packages/adblocker-benchmarks/blockers/adblockplus.js
  packages/adblocker-benchmarks/blockers/adblockpluscore-index.js
  packages/adblocker-benchmarks/package.json
Labels: PR: Internal :house:

#2119 Do not initialize PSL in hosts-only mode
  packages/adblocker-benchmarks/blockers/ublock.js
  packages/adblocker-benchmarks/run.js
Labels: PR: Internal :house:

#2124 Add hosts-lookup
  packages/adblocker-benchmarks/Makefile
  packages/adblocker-benchmarks/blockers/hosts-lookup.js
  packages/adblocker-benchmarks/package.json
  packages/adblocker-benchmarks/run.js
Labels: PR: Internal :house:

#2126 Fix easylist.txt at runtime
  packages/adblocker-benchmarks/blockers/adblockplus.js
  packages/adblocker-benchmarks/run.js
Labels: PR: Internal :house:

#2128 Drop filters with regular expression assertions
  packages/adblocker-benchmarks/run.js
Labels: PR: Internal :house:

#2136 Use tsurlfilter's DNS engine
  packages/adblocker-benchmarks/blockers/tsurlfilter.js
Labels: PR: Internal :house:

#2140 Make UBlockOrigin#deserialize() consistent
  packages/adblocker-benchmarks/blockers/ublock.js
Labels: PR: Internal :house:

#2141 Fix Node.js package names in make clean
  packages/adblocker-benchmarks/Makefile
Labels: PR: Internal :house:

#2143 Add support for exceptions to hosts-lookup
  packages/adblocker-benchmarks/blockers/hosts-lookup.js
Labels: PR: Internal :house:

#2144 Install fast-hosts-lookup like other engines
  packages/adblocker-benchmarks/Makefile
  packages/adblocker-benchmarks/package.json
Labels: PR: Internal :house:

#2145 Use specific versions of the engines
  packages/adblocker-benchmarks/Makefile
  packages/adblocker-benchmarks/package.json
Labels: PR: Internal :house:

#2148 Remove dependence on yarn
  packages/adblocker-benchmarks/package.json
Labels: PR: Internal :house:

#2150 Add SKIP_SERIALIZATION=1 flag
  packages/adblocker-benchmarks/Makefile
  packages/adblocker-benchmarks/run.js
Labels: PR: Internal :house:

#2149 Handle 'ping' type from puppeteer
  packages/adblocker-benchmarks/run.js
Labels: PR: Internal :house:

#2152 Update requests.json
  packages/adblocker-benchmarks/Makefile
Labels: PR: Internal :house:

#2153 Pass --compressed to curl
  packages/adblocker-benchmarks/Makefile
Labels: PR: Internal :house:

#2154 Update easylist.txt
  packages/adblocker-benchmarks/easylist.txt
  packages/adblocker-benchmarks/easyprivacy.txt
  packages/adblocker-benchmarks/run.js
Labels: PR: Internal :house:

#2156 Add DEBUG=1 flag
  packages/adblocker-benchmarks/Makefile
  packages/adblocker-benchmarks/blockers/adblockplus.js
  packages/adblocker-benchmarks/blockers/tsurlfilter.js
  packages/adblocker-benchmarks/run.js
Labels: PR: Internal :house:

#2159 Add COMPARE=<filename> option
  packages/adblocker-benchmarks/Makefile
  packages/adblocker-benchmarks/run.js
Labels: PR: Internal :house:

#2161 Add local .gitignore
  .gitignore
  packages/adblocker-benchmarks/.gitignore
Labels: PR: Internal :house:

#2160 Add matchDebug() to uBO's proxy API
  packages/adblocker-benchmarks/blockers/ublock.js
Labels: PR: Internal :house:

#2162 Add matchDebug() for Cliqz
  packages/adblocker-benchmarks/blockers/cliqz-base.js
  packages/adblocker-benchmarks/blockers/cliqz-compression.js
  packages/adblocker-benchmarks/blockers/cliqz.js
  packages/adblocker-benchmarks/run.js
Labels: PR: Internal :house:

#2163 Move benchmarking to separate benchmark() function
  packages/adblocker-benchmarks/run.js
Labels: PR: Internal :house:

#2171 Add 'ping' mapping in blockers/tsurlfilter.js
  packages/adblocker-benchmarks/blockers/tsurlfilter.js
Labels: PR: Internal :house:

#2172 Add Adblock Plus whitelisting logic
  packages/adblocker-benchmarks/blockers/adblockplus.js
Labels: PR: Internal :house:

#2180 Fix "bootstrap" in README.md
  README.md
Labels: PR: Docs :memo:

#2187 Always skip last token unless anchored
  packages/adblocker/src/filters/network.ts
Labels: PR: Bug Fix :bug:
