Repository ghostery/adblocker, pull requests merged in 2021-12, with the labels that each got.

#2341 Add missing list
  packages/adblocker/assets/ublock-origin/filters-2021.txt
  packages/adblocker/assets/update.js
  packages/adblocker/src/fetch.ts
Labels: PR: Polish :nail_care:

#2342 Updated ubo-core to latest version
  packages/adblocker-benchmarks/Makefile
  packages/adblocker-benchmarks/package.json
Labels: PR: Internal :house:

#2343 Update Puppeteer Cooperative Intercept Mode
  packages/adblocker-puppeteer-example/package.json
  packages/adblocker-puppeteer/adblocker.ts
  packages/adblocker-puppeteer/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:
