Repository ghostery/adblocker, pull requests merged in 2022-08, with the labels that each got.

#2767 Fix generation of compression codebooks
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:

#2768 Preserve all information in rawLine (fix for the blank screen in YouTube full screen mode)
  packages/adblocker/src/filters/cosmetic.ts
Labels: PR: Bug Fix :bug:

#2771 Fixing CI ("benchmark" action is failing)
  .github/workflows/benchmark.yml
  packages/adblocker-benchmarks/Makefile
  packages/adblocker-benchmarks/package.json
Labels: PR: Internal :house:

#2782 Use "pagehide" instead of "unload"
  packages/adblocker-webextension-cosmetics/adblocker.ts
Labels: PR: Performance :running_woman:

#2786 ci: do not run benchmarks on dependabot PRs
  .github/workflows/benchmark.yml
Labels: PR: Internal :house:

#2750 New option "enablePushInjectionsOnNavigationEvents"
  packages/adblocker-webextension-example/manifest.json
  packages/adblocker-webextension/adblocker.ts
  packages/adblocker/src/config.ts
Labels: PR: New Feature :rocket:
