Repository ghostery/adblocker, pull requests merged in 2022-03, with the labels that each got.

#2506 Don't throw an error when receiving a message from popup
  packages/adblocker-webextension/adblocker.ts
Labels: PR: Bug Fix :bug:

#2496 cosmetics: make sure we do not hide body or html elements
  packages/adblocker-content/adblocker.ts
  packages/adblocker-webextension-cosmetics/adblocker.ts
Labels: PR: Polish :nail_care:

#2515 Fix publishing
  .github/workflows/release.yml
Labels: PR: Bug Fix :bug:

#2516 Revert release fix since the issue was a token permission missing
  .github/workflows/release.yml
Labels: PR: Bug Fix :bug:

#2531 Don't run assets updates on forks.
  .github/workflows/assets.yml
Labels: PR: Internal :house:
