Repository ghostery/adblocker, pull requests merged in 2023-02, with the labels that each got.

#3064 Implement metadata abstraction
  .gitignore
  packages/adblocker/package.json
  packages/adblocker/src/data-view.ts
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/src/engine/map.ts
  packages/adblocker/src/engine/metadata.ts
  packages/adblocker/src/engine/metadata/categories.ts
  packages/adblocker/src/engine/metadata/organizations.ts
  packages/adblocker/src/engine/metadata/patterns.ts
  packages/adblocker/src/engine/reverse-index.ts
  packages/adblocker/test/data/trackerdb_20221213.json.gz
  packages/adblocker/test/engine/metadata.test.ts
  packages/adblocker/test/utils.ts
  packages/adblocker/tools/bench-metadata.ts
Labels: PR: New Feature :rocket:

#3081 Fix codebooks generation
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:

#3082 Fix README badges
  README.md
Labels: PR: Docs :memo:
