Repository ghostery/adblocker, pull requests merged in 2024-12, with the labels that each got.

#4492 Fix assets update CI
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:

#4488 chore: use `Frame.detached` for puppeteer
  packages/adblocker-puppeteer/src/index.ts
Labels: PR: Internal :house:

#4500 Fix: hidingStyles should not be cached
  packages/adblocker/src/engine/bucket/cosmetic.ts
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/test/engine/engine.test.ts
Labels: PR: Bug Fix :bug:

#4506 fix: custom styles being ignored for pure has filters
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/test/engine/engine.test.ts
Labels: PR: Bug Fix :bug:

#4505 fix: `CosmeticFilter.toString()` ignoring custom style
  packages/adblocker/src/filters/cosmetic.ts
Labels: PR: Bug Fix :bug:

#4487 chore: fix `@typescript-eslint/no-unsafe-member-access`
  packages/adblocker/tools/stress-test-engine-update.ts
Labels: PR: Internal :house:

#4495 feat: override config when merging
  packages/adblocker/src/engine/engine.ts
Labels: PR: New Feature :rocket:

#4499 Split cosmetic matching from injection
  packages/adblocker/src/engine/engine.ts
Labels: PR: New Feature :rocket:

#4519 Merge: allow config differences
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/test/engine/engine.test.ts
Labels: PR: Bug Fix :bug:

#4520 fix(test): drop `.only`
  packages/adblocker/test/engine/engine.test.ts
Labels: PR: Internal :house:

#4555 fix: cosmetic selector codebook generation
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:
