Repository ghostery/adblocker, pull requests merged in 2024-07, with the labels that each got.

#4053 Update typescript
  package.json
  packages/adblocker-content/package.json
  packages/adblocker-electron-example/package.json
  packages/adblocker-electron-preload/package.json
  packages/adblocker-electron/package.json
  packages/adblocker-extended-selectors/package.json
  packages/adblocker-playwright-example/package.json
  packages/adblocker-playwright/package.json
  packages/adblocker-puppeteer-example/package.json
  packages/adblocker-puppeteer/package.json
  packages/adblocker-webextension-cosmetics/package.json
  packages/adblocker-webextension-example/package.json
  packages/adblocker-webextension/package.json
  packages/adblocker/package.json
  tsconfig.json
  yarn.lock
Labels: PR: Dependencies :nut_and_bolt:

#4071 Optimise DOM mutation handling in `DOMMonitor`
  packages/adblocker-content/adblocker.ts
  packages/adblocker-webextension-cosmetics/test/adblocker.test.ts
Labels: PR: New Feature :rocket:

#4094 Fix asset update
  packages/adblocker/assets/update.js
  packages/adblocker/tsconfig.json
Labels: PR: Internal :house:

#4096 Fix codebook generation
  packages/adblocker/package.json
  packages/adblocker/tools/auto-bump-engine-version.ts
  packages/adblocker/tools/engine-size.ts
  packages/adblocker/tools/generate_compression_codebooks.ts
  packages/adblocker/tools/priorities.ts
Labels: PR: Internal :house:

#4098 tsx to run typescript
  .mocharc.json
  .tool-versions
  package.json
  packages/adblocker-electron-example/index.js
  packages/adblocker-electron-example/package.json
  packages/adblocker-electron-example/tsconfig.json
  packages/adblocker-electron/package.json
  packages/adblocker-extended-selectors/package.json
  packages/adblocker-playwright-example/package.json
  packages/adblocker-playwright-example/tsconfig.json
  packages/adblocker-puppeteer-example/package.json
  packages/adblocker-puppeteer-example/tsconfig.json
  packages/adblocker-puppeteer/package.json
  packages/adblocker-webextension-cosmetics/package.json
  packages/adblocker-webextension/package.json
  packages/adblocker/package.json
  packages/adblocker/src/index.ts
  tsconfig.json
  yarn.lock
Labels: PR: Internal :house:

#4104 Drop unused tsconfig.json by #4098
  packages/adblocker/tools/tsconfig.json
Labels: PR: Internal :house:

#4101 Enforce PR labels
  .github/workflows/enforce-labels.yml
  package.json
  yarn.lock
Labels: PR: Internal :house:

#4102 Update ESLint configuration for test files
  eslint.config.js
  packages/adblocker-electron/package.json
  packages/adblocker-extended-selectors/package.json
  packages/adblocker-extended-selectors/tsconfig.json
  packages/adblocker/package.json
  packages/adblocker/src/engine/bucket/cosmetic.ts
  packages/adblocker/src/resources.ts
  packages/adblocker/test/data/requests.ts
  packages/adblocker/test/engine/metadata.test.ts
  packages/adblocker/test/filters-size-estimation.test.ts
  packages/adblocker/test/matching.test.ts
  packages/adblocker/test/request.test.ts
  packages/adblocker/test/reverse-index.test.ts
  packages/adblocker/test/utils.test.ts
  packages/adblocker/test/utils.ts
Labels: PR: Internal :house:

#4103 Run examples in both commonjs and esm
  packages/adblocker-electron-example/README.md
  packages/adblocker-electron-example/index.js
  packages/adblocker-electron-example/package.json
  packages/adblocker-electron-example/src/index.ts
  packages/adblocker-electron-example/tsconfig.json
  packages/adblocker-playwright-example/README.md
  packages/adblocker-playwright-example/package.json
  packages/adblocker-playwright-example/src/index.ts
  packages/adblocker-playwright-example/tsconfig.json
  packages/adblocker-puppeteer-example/README.md
  packages/adblocker-puppeteer-example/package.json
  packages/adblocker-puppeteer-example/src/index.ts
  packages/adblocker-puppeteer-example/tsconfig.json
  yarn.lock
Labels: PR: Internal :house:

#3881 Improve engine events to expose internal workflow
  packages/adblocker-electron-example/src/index.ts
  packages/adblocker-electron/src/index.ts
  packages/adblocker-playwright-example/src/index.ts
  packages/adblocker-puppeteer-example/src/index.ts
  packages/adblocker-webextension-example/background.ts
  packages/adblocker-webextension/src/index.ts
  packages/adblocker/src/engine/bucket/cosmetic.ts
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/src/events.ts
  packages/adblocker/test/engine/engine.test.ts
Labels: PR: New Feature :rocket:

#4108 Feedback from not supported filters
  packages/adblocker/src/lists.ts
  packages/adblocker/test/lists.test.ts
Labels: PR: New Feature :rocket:

#4119 CI: fix failures node 22.5.0
  .github/workflows/assets.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .tool-versions
  package.json
  yarn.lock
Labels: PR: Internal :house:

#4153 ci: rollback to use v22.5.1
  .github/workflows/tests.yml
Labels: PR: Polish :nail_care:
