Repository ghostery/adblocker, pull requests merged in 2024-10, with the labels that each got.

#4320 Update webextension-polyfill
  packages/adblocker-webextension-example/background.ts
  packages/adblocker-webextension-example/package.json
  packages/adblocker-webextension/README.md
  packages/adblocker-webextension/package.json
  packages/adblocker-webextension/src/index.ts
  packages/adblocker-webextension/test/index.test.ts
  yarn.lock
Labels: PR: Internal :house:

#4355 CI: fix puppeteer + run tests one after another
  package.json
  packages/adblocker-puppeteer/test/index.test.ts
Labels: PR: Internal :house:

#4365 Fix: bring back resources.txt
  packages/adblocker/assets/ublock-origin/resources.json
  packages/adblocker/assets/ublock-origin/resources.txt
  packages/adblocker/assets/update.js
Labels: PR: Internal :house:

#4366 Rename from @cliqz/adblocker to @ghostery/adblocker
  CHANGELOG.md
  README.md
  bench/comparison/README.md
  bench/comparison/package.json
  bench/comparison/yarn.lock
  bench/micro.ts
  bench/utils.ts
  packages/adblocker-content/README.md
  packages/adblocker-content/package.json
  packages/adblocker-content/src/index.ts
  packages/adblocker-electron-example/README.md
  packages/adblocker-electron-example/package.json
  packages/adblocker-electron-example/src/index.ts
  packages/adblocker-electron-preload/README.md
  packages/adblocker-electron-preload/package.json
  packages/adblocker-electron-preload/src/index.ts
  packages/adblocker-electron/README.md
  packages/adblocker-electron/package.json
  packages/adblocker-electron/src/index.ts
  packages/adblocker-electron/src/preload_path-cjs.cts
  packages/adblocker-electron/src/preload_path.ts
  packages/adblocker-extended-selectors/README.md
  packages/adblocker-extended-selectors/package.json
  packages/adblocker-playwright-example/README.md
  packages/adblocker-playwright-example/package.json
  packages/adblocker-playwright-example/src/index.ts
  packages/adblocker-playwright/README.md
  packages/adblocker-playwright/package.json
  packages/adblocker-playwright/src/index.ts
  packages/adblocker-puppeteer-example/README.md
  packages/adblocker-puppeteer-example/package.json
  packages/adblocker-puppeteer-example/src/index.ts
  packages/adblocker-puppeteer/README.md
  packages/adblocker-puppeteer/package.json
  packages/adblocker-puppeteer/src/index.ts
  packages/adblocker-webextension-cosmetics/README.md
  packages/adblocker-webextension-cosmetics/package.json
  packages/adblocker-webextension-cosmetics/src/index.ts
  packages/adblocker-webextension-example/README.md
  packages/adblocker-webextension-example/background.ts
  packages/adblocker-webextension-example/content-script.ts
  packages/adblocker-webextension-example/package.json
  packages/adblocker-webextension/README.md
  packages/adblocker-webextension/package.json
  packages/adblocker-webextension/src/index.ts
  packages/adblocker-webextension/test/index.test.ts
  packages/adblocker/README.md
  packages/adblocker/assets/update.js
  packages/adblocker/package.json
  packages/adblocker/src/engine/bucket/cosmetic.ts
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/src/filters/cosmetic.ts
  yarn.lock
Labels: PR: Breaking Change :boom:

#4373 Fixed a typo in the title
  packages/adblocker-webextension/README.md
Labels: PR: Docs :memo:

#4278 packages: adblocker-electron{-preload}: make use of `executeJavaScript`
  packages/adblocker-electron-preload/src/index.ts
  packages/adblocker-electron/src/index.ts
Labels: PR: Bug Fix :bug:

#4376 fix: exception of script injection not respecting aliases
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/src/filters/cosmetic.ts
  packages/adblocker/src/resources.ts
  packages/adblocker/test/engine/engine.test.ts
Labels: PR: Bug Fix :bug:

#4395 docs: update references in examples
  packages/adblocker-electron-example/README.md
  packages/adblocker-playwright-example/README.md
  packages/adblocker-puppeteer-example/README.md
Labels: PR: Docs :memo:

#4403 Fix codebook generation ngram size
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:

#4394 fix: allow resources surrogates
  packages/adblocker/src/resources.ts
  packages/adblocker/test/resources.test.ts
Labels: PR: Bug Fix :bug:
