Repository ghostery/adblocker, pull requests merged in 2024-11, with the labels that each got.

#4431 CI: increast time limit for assets update
  .github/workflows/assets.yml
Labels: PR: Internal :house:

#4413 docs: Fix build badges
  bench/comparison/README.md
  packages/adblocker-content/README.md
  packages/adblocker-electron-example/README.md
  packages/adblocker-electron-preload/README.md
  packages/adblocker-electron/README.md
  packages/adblocker-extended-selectors/README.md
  packages/adblocker-playwright/README.md
  packages/adblocker-puppeteer-example/README.md
  packages/adblocker-puppeteer/README.md
  packages/adblocker-webextension/README.md
  packages/adblocker/README.md
Labels: PR: Docs :memo:

#4455 feat: Optional support for native :has pseudo classes
  packages/adblocker-extended-selectors/src/index.ts
  packages/adblocker-extended-selectors/src/parse.ts
  packages/adblocker/src/engine/bucket/cosmetic.ts
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/src/filters/cosmetic.ts
  packages/adblocker/test/engine/engine.test.ts
Labels: PR: New Feature :rocket:

#4465 fix(benchmark): convert cjs to nodenext
  bench/Makefile
  bench/micro.ts
  bench/requests.ts
  bench/run_benchmark.ts
  bench/tsconfig.json
  eslint.config.js
Labels: PR: Internal :house:

#4476 chore: export referenceable components
  packages/adblocker/src/index.ts
  packages/adblocker/src/lists.ts
Labels: PR: Internal :house:
