Repository ghostery/adblocker, pull requests merged in 2024-08, with the labels that each got.

#4157 fix(adblocker-electron): `An object could not be cloned`
  packages/adblocker-content/src/index.ts
Labels: PR: Bug Fix :bug:

#4174 Fix retrieval of latestRevision in assets update script
  packages/adblocker/assets/update.js
Labels: PR: Bug Fix :bug:

#4176 Fix raw-cosmetic codebook generation
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:

#4177 Fix cosmetic-selector codebook generation
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:

#4186 Fix FilterEngine static merge method
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/test/engine/engine.test.ts
Labels: PR: Bug Fix :bug:

#4199 Lazy initialise adblocker engine tests
  packages/adblocker/test/engine/engine.test.ts
Labels: PR: Internal :house:

#4200 Network filters options value
  packages/adblocker/src/filters/network.ts
  packages/adblocker/src/utils.ts
  packages/adblocker/test/parsing.test.ts
  packages/adblocker/test/utils.test.ts
Labels: PR: Internal :house:

#4205 $redirect priority
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/src/filters/network.ts
  packages/adblocker/test/engine/engine.test.ts
  packages/adblocker/test/parsing.test.ts
Labels: PR: Bug Fix :bug:

#3897 feat: implement `$replace` modifier, improve option parsing
  packages/adblocker-webextension/package.json
  packages/adblocker-webextension/src/index.ts
  packages/adblocker-webextension/test/index.test.ts
  packages/adblocker/src/engine/bucket/cosmetic.ts
  packages/adblocker/src/engine/bucket/html.ts
  packages/adblocker/src/engine/bucket/network.ts
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/src/engine/optimizer.ts
  packages/adblocker/src/filters/cosmetic.ts
  packages/adblocker/src/filters/network.ts
  packages/adblocker/src/html-filtering.ts
  packages/adblocker/src/request.ts
  packages/adblocker/test/data/samples/https___alliptvlinks.com_tktk_content_plugins_rwa__t____r__v__ebt_l_ym___45_gzw__ql_k____vj____h__i___v_9.js.br
  packages/adblocker/test/data/samples/https___alliptvlinks.com_tktk_content_plugins_rwa__t____r__v__ebt_l_ym___45_gzw__ql_k____vj____h__i___v_9.js.modified.br
  packages/adblocker/test/data/samples/https___bitcotasks.com_assets_js_mainjs.php.br
  packages/adblocker/test/data/samples/https___bitcotasks.com_assets_js_mainjs.php.modified.br
  packages/adblocker/test/data/samples/https___rekidai_info.github.io__app_immutable_components_pages_index__page.svelte_74656d8d.js.br
  packages/adblocker/test/data/samples/https___rekidai_info.github.io__app_immutable_components_pages_index__page.svelte_74656d8d.js.modified.br
  packages/adblocker/test/data/samples/https___www.youtube.com_watch_v_4t_r_e4_iyg.html.br
  packages/adblocker/test/data/samples/https___www.youtube.com_watch_v_4t_r_e4_iyg.html.modified.br
  packages/adblocker/test/data/samples/readme.md
  packages/adblocker/test/engine/engine.test.ts
  packages/adblocker/test/html-filtering.test.ts
  packages/adblocker/test/parsing.test.ts
  packages/adblocker/test/utils.ts
Labels: PR: New Feature :rocket:

#4215 feat: allow overriding `DEFAULT_HIDING_STYLE`
  packages/adblocker/src/engine/bucket/cosmetic.ts
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/src/filters/cosmetic.ts
  packages/adblocker/test/engine/engine.test.ts
  packages/adblocker/test/parsing.test.ts
Labels: PR: New Feature :rocket:

#4238 Override hiding style in `CosmeticBucket.getCosmeticsFilters`
  packages/adblocker/src/engine/bucket/cosmetic.ts
  packages/adblocker/src/engine/engine.ts
Labels: PR: Bug Fix :bug:
