Repository ghostery/adblocker, pull requests merged in 2024-02, with the labels that each got.

#3764 Update assets + fix codebooks generation
  packages/adblocker/assets/easylist/easylist-cookie.txt
  packages/adblocker/assets/easylist/easylist.txt
  packages/adblocker/assets/easylist/easylistgermany.txt
  packages/adblocker/assets/easylist/easyprivacy.txt
  packages/adblocker/assets/peter-lowe/serverlist.txt
  packages/adblocker/assets/ublock-origin/annoyances-cookies.txt
  packages/adblocker/assets/ublock-origin/annoyances-others.txt
  packages/adblocker/assets/ublock-origin/badware.txt
  packages/adblocker/assets/ublock-origin/filters-2020.txt
  packages/adblocker/assets/ublock-origin/filters-2021.txt
  packages/adblocker/assets/ublock-origin/filters-2022.txt
  packages/adblocker/assets/ublock-origin/filters-2023.txt
  packages/adblocker/assets/ublock-origin/filters-mobile.txt
  packages/adblocker/assets/ublock-origin/filters.txt
  packages/adblocker/assets/ublock-origin/privacy.txt
  packages/adblocker/assets/ublock-origin/quick-fixes.txt
  packages/adblocker/assets/ublock-origin/resource-abuse.txt
  packages/adblocker/assets/ublock-origin/resources.txt
  packages/adblocker/assets/ublock-origin/unbreak.txt
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:

#3773 chore: fix filters links + add missing
  packages/adblocker/assets/easylist/easylist-cookie.txt
  packages/adblocker/assets/easylist/easylist.txt
  packages/adblocker/assets/easylist/easylistgermany.txt
  packages/adblocker/assets/easylist/easyprivacy.txt
  packages/adblocker/assets/peter-lowe/serverlist.txt
  packages/adblocker/assets/ublock-origin/annoyances-others.txt
  packages/adblocker/assets/ublock-origin/badware.txt
  packages/adblocker/assets/ublock-origin/filters-2020.txt
  packages/adblocker/assets/ublock-origin/filters-2022.txt
  packages/adblocker/assets/ublock-origin/filters-2023.txt
  packages/adblocker/assets/ublock-origin/filters-2024.txt
  packages/adblocker/assets/ublock-origin/filters-mobile.txt
  packages/adblocker/assets/ublock-origin/filters.txt
  packages/adblocker/assets/ublock-origin/quick-fixes.txt
  packages/adblocker/assets/ublock-origin/unbreak.txt
  packages/adblocker/assets/update.js
Labels: PR: Internal :house:

#3777 Ghostery assets
  packages/adblocker/assets/easylist/easylist-cookie.txt
  packages/adblocker/assets/easylist/easylist.txt
  packages/adblocker/assets/easylist/easyprivacy.txt
  packages/adblocker/assets/peter-lowe/serverlist.txt
  packages/adblocker/assets/ublock-origin/annoyances-cookies.txt
  packages/adblocker/assets/ublock-origin/annoyances-others.txt
  packages/adblocker/assets/ublock-origin/badware.txt
  packages/adblocker/assets/ublock-origin/filters-2020.txt
  packages/adblocker/assets/ublock-origin/filters-2021.txt
  packages/adblocker/assets/ublock-origin/filters-2022.txt
  packages/adblocker/assets/ublock-origin/filters-2023.txt
  packages/adblocker/assets/ublock-origin/filters-2024.txt
  packages/adblocker/assets/ublock-origin/filters.txt
  packages/adblocker/assets/ublock-origin/privacy.txt
  packages/adblocker/assets/ublock-origin/quick-fixes.txt
  packages/adblocker/assets/ublock-origin/resource-abuse.txt
  packages/adblocker/assets/ublock-origin/unbreak.txt
  packages/adblocker/assets/update.js
Labels: PR: Internal :house:

#3788 Fix assets
  packages/adblocker/adblocker.ts
  packages/adblocker/assets/easylist/easylist-cookie.txt
  packages/adblocker/assets/easylist/easylist.txt
  packages/adblocker/assets/easylist/easylistgermany.txt
  packages/adblocker/assets/easylist/easyprivacy.txt
  packages/adblocker/assets/peter-lowe/serverlist.txt
  packages/adblocker/assets/ublock-origin/annoyances-cookies.txt
  packages/adblocker/assets/ublock-origin/annoyances-others.txt
  packages/adblocker/assets/ublock-origin/annoyances.txt
  packages/adblocker/assets/ublock-origin/badware.txt
  packages/adblocker/assets/ublock-origin/filters-2020.txt
  packages/adblocker/assets/ublock-origin/filters-2021.txt
  packages/adblocker/assets/ublock-origin/filters-2022.txt
  packages/adblocker/assets/ublock-origin/filters-2023.txt
  packages/adblocker/assets/ublock-origin/filters-2024.txt
  packages/adblocker/assets/ublock-origin/filters-mobile.txt
  packages/adblocker/assets/ublock-origin/filters.txt
  packages/adblocker/assets/ublock-origin/privacy.txt
  packages/adblocker/assets/ublock-origin/quick-fixes.txt
  packages/adblocker/assets/ublock-origin/resources.txt
  packages/adblocker/assets/ublock-origin/unbreak.txt
  packages/adblocker/src/codebooks/cosmetic-selector.ts
  packages/adblocker/src/codebooks/network-filter.ts
  packages/adblocker/src/codebooks/network-hostname.ts
  packages/adblocker/src/codebooks/network-redirect.ts
  packages/adblocker/src/codebooks/raw-network.ts
  packages/adblocker/src/engine/domains.ts
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/src/fetch.ts
  packages/adblocker/src/filters/cosmetic.ts
  packages/adblocker/src/filters/network.ts
  packages/adblocker/src/request.ts
  packages/adblocker/src/resources.ts
  packages/adblocker/src/utils.ts
  packages/adblocker/test/resources.test.ts
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:

#3792 Fix breakage with deleted assets
  packages/adblocker/assets/easylist/easylistgermany.txt
  packages/adblocker/assets/ublock-origin/annoyances.txt
  packages/adblocker/assets/ublock-origin/filters-mobile.txt
Labels: PR: Internal :house:

#3798 fix: use absolute paths for preload, closes #2756
  packages/adblocker-electron/adblocker.ts
Labels: PR: Polish :nail_care:

#3801 Update auto - fix release pipeline
  package.json
  yarn.lock
Labels: PR: Bug Fix :bug:
