Repository ghostery/adblocker, pull requests merged in 2025-01, with the labels that each got.

#4567 fix: cosmetic codebook generation
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:

#4564 fix(adblocker-webextension): incorrect use of webextension-polyfill
  packages/adblocker-webextension-example/background.ts
  packages/adblocker-webextension/src/index.ts
Labels: PR: Internal :house:

#4525 fix: check domains validity when parsing network filters
  packages/adblocker/src/engine/domains.ts
  packages/adblocker/src/filters/cosmetic.ts
  packages/adblocker/src/filters/network.ts
  packages/adblocker/test/parsing.test.ts
Labels: PR: Bug Fix :bug:

#4518 refactor: replace `fastStartsWith` & `fastStartsWithFrom`
  packages/adblocker/src/filters/cosmetic.ts
  packages/adblocker/src/filters/network.ts
  packages/adblocker/src/lists.ts
  packages/adblocker/src/utils.ts
Labels: PR: Performance :running_woman:

#4524 feat: `to` network modifier
  packages/adblocker/src/engine/domains.ts
  packages/adblocker/src/filters/network.ts
  packages/adblocker/test/matching.test.ts
  packages/adblocker/test/parsing.test.ts
Labels: PR: New Feature :rocket:

#4626 fix(ci): codebook generation
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:

#4635 fix(internal): cosmetic selector asset generation
  packages/adblocker/tools/generate_compression_codebooks.ts
Labels: PR: Internal :house:
