Repository ghostery/adblocker, pull requests merged in 2025-07, with the labels that each got.

#4932 Extended selectors: matches-css
  .github/workflows/tests.yml
  packages/adblocker-extended-selectors/.gitignore
  packages/adblocker-extended-selectors/package.json
  packages/adblocker-extended-selectors/playwright.config.ts
  packages/adblocker-extended-selectors/src/eval.ts
  packages/adblocker-extended-selectors/src/extended.ts
  packages/adblocker-extended-selectors/test/e2e/browser.test.ts
  packages/adblocker-extended-selectors/test/unit/eval.test.ts
  packages/adblocker-extended-selectors/test/unit/extended.test.ts
  packages/adblocker-extended-selectors/test/unit/parse.test.ts
  packages/adblocker-playwright-example/package.json
  packages/adblocker-playwright/package.json
  packages/adblocker/test/parsing.test.ts
  yarn.lock
Labels: PR: New Feature :rocket:

#4982 fix(adblocker-electron): use `session.registerPreloadScript`
  packages/adblocker-electron/src/index.ts
Labels: PR: Bug Fix :bug:

#4974 fix(adblocker-extended-selector): `compound` with `complex`
  packages/adblocker-extended-selectors/src/eval.ts
  packages/adblocker-extended-selectors/test/unit/eval.test.ts
Labels: PR: Bug Fix :bug:

#5013 Adblocker: relax merge config consistancy check
  packages/adblocker/src/engine/engine.ts
  packages/adblocker/test/engine/engine.test.ts
Labels: PR: Bug Fix :bug:

#5038 chore(internal): update `playwright` ecosystem
  packages/adblocker-extended-selectors/package.json
  packages/adblocker-playwright-example/package.json
  packages/adblocker-playwright/package.json
  yarn.lock
Labels: PR: Dependencies :nut_and_bolt:
